enum ErrorCodes {
    EOP_CANCEL = 'EOP_CANCEL',

    EACCES_FILE = 'EACCES_FILE',
    EACCES_STEAM = 'EACCES_STEAM',
    EACCES_BROWSER = 'EACCES_BROWSER',

    ECONNREFUSED_REMOTE_MOD = 'ECONNREFUSED_REMOTE_MOD',
    ECONNREFUSED_REMOTE_PAGE = 'ECONNREFUSED_REMOTE_PAGE',
    ECONNREFUSED_MODEL_RESP = 'ECONNREFUSED_MODEL_RESP',

    ENOENT_FILE = 'ENOENT_FILE',
    ENOENT_APP = 'ENOENT_APP',
    ENOENT_MOD_DIR = 'ENOENT_MOD_DIR',
    ENOENT_MOD_CONFIG = 'ENOENT_MOD_CONFIG',
    ENOENT_REMOTE_MOD = 'ENOENT_REMOTE_MOD',
    ENOENT_NATIVE_MOD = 'ENOENT_NATIVE_MOD',
    ENOENT_NATIVE_MOD_EMPTY = 'ENOENT_NATIVE_MOD_EMPTY',

    ENOTFOUND_NEXUSMOD_URL = 'ENOTFOUND_NEXUSMOD_URL',

    EINVAL_XML_DATA = 'EINVAL_XML_DATA',
    EINVAL_MOD_QUERY = 'EINVAL_MOD_QUERY',
    EINVAL_MOD_CONFIG = 'EINVAL_MOD_CONFIG',
    EINVAL_MODEL_KEY = 'EINVAL_MODEL_KEY',
    EINVAL_MODEL_RESP = 'EINVAL_MODEL_RESP',
    EINVAL_LANG_FILE_EMPTY = 'EINVAL_LANG_FILE_EMPTY',
    EINVAL_LANG_OPTS_EMPTY = 'EINVAL_LANG_OPTS_EMPTY',
}

export default ErrorCodes;
